# Generated by Django 3.2.7 on 2021-10-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('text', models.CharField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievement_image', verbose_name='Картинка')),
                ('y_coin', models.PositiveIntegerField(default=0, verbose_name='Награда в валюте')),
                ('f_coin', models.PositiveIntegerField(default=0, verbose_name='Награда факультету')),
                ('map_type', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
    ]
