# Generated by Django 3.2.7 on 2021-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_image', verbose_name='Картинка'),
        ),
    ]
