# Generated by Django 3.2.7 on 2021-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_question_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Контрольный срок'),
        ),
    ]
