# Generated by Django 3.2.7 on 2021-10-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
    ]
