# Generated by Django 3.2.7 on 2021-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('accounts', '0003_auto_20211002_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achievement',
            field=models.ManyToManyField(blank=True, null=True, to='achievements.Achievement'),
        ),
    ]
