# Generated by Django 3.2.7 on 2021-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='y_coin',
            field=models.FloatField(default=0.0, verbose_name='Валюта'),
        ),
    ]
