# Generated by Django 3.2.7 on 2021-10-01 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(blank=True, choices=[('in_work', 'В работе'), ('handed_over_to_delivery', 'Передано в доставку'), ('awaiting_receipt', 'Ожидает получения'), ('received', 'Получено')], default='in_work', max_length=50, verbose_name='Статус')),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.shopitem', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'verbose_name_plural': 'Товары магазина',
            },
        ),
    ]
