# Generated by Django 3.2.7 on 2021-10-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_purchases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Мой заказ', 'verbose_name_plural': 'Мои заказы'},
        ),
    ]
